FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY requirements.txt .
COPY requirements-test.txt .

RUN pip install --no-cache-dir -r requirements-test.txt

COPY app ./app
COPY tests ./tests

CMD ["python", "-m", "pytest", "-q"]
